-- Schema
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
-------
-- Tables

CREATE TABLE compte(
   id_compte BIGINT GENERATED BY DEFAULT AS IDENTITY,
   pseudo VARCHAR(25)  NOT NULL,
   email VARCHAR(50)  NOT NULL,
   empreinte_mdp VARCHAR(68)  NOT NULL,
   role_admin BOOLEAN NOT NULL DEFAULT FALSE,
   PRIMARY KEY(id_compte),
   UNIQUE(pseudo),
   UNIQUE(email)
);



CREATE TABLE Organisateur_d_hackaton(
   id_organisateur SERIAL,
   nom_org VARCHAR(50) NOT NULL,
   Adres_mail_org VARCHAR(50) NOT NULL,
   PRIMARY KEY(id_organisateur)
);

CREATE TABLE Hachaton(
   id_hack SERIAL,
   Nom_hack VARCHAR(50) NOT NULL,
   Theme_hach VARCHAR(50) NOT NULL,
   Heure_deb TIME NOT NULL,
   Date_bed DATE,
   Date_fin DATE,
   Lieu_hack VARCHAR(50) NOT NULL,
   Contact VARCHAR(50),
   id_organisateur INT NOT NULL,
   PRIMARY KEY(id_hack),
   FOREIGN KEY(id_organisateur) REFERENCES Organisateur_d_hackaton(id_organisateur)
);

CREATE TABLE Menbre_staff(
   id_menstaf SERIAL,
   Nom_menstaf VARCHAR(50) NOT NULL,
   adres_mail_manstaf VARCHAR(50),
   Age INT,
   PRIMARY KEY(id_menstaf)
);

CREATE TABLE Etudiant(
   id_etudiant SERIAL,
   Nom_etudiant VARCHAR(50),
   Etablissement_etudiant VARCHAR(50) NOT NULL,
   addresse_mail_etudiant VARCHAR(50) NOT NULL,
   PRIMARY KEY(id_etudiant)
);

CREATE TABLE Recompense(
   id_recompense SERIAL,
   type_recompense VARCHAR(50) NOT NULL,
   Nom_recompense VARCHAR(50) NOT NULL,
   PRIMARY KEY(id_recompense)
);

CREATE TABLE Juge(
   id_juge SERIAL,
   Nom_juge VARCHAR(50) NOT NULL,
   Adresse_mail_juge VARCHAR(50) NOT NULL,
   Specialite VARCHAR(50) NOT NULL,
   PRIMARY KEY(id_juge)
);

CREATE TABLE Partenaire(
   id_partenaire SERIAL,
   Nom_partenaire VARCHAR(50) NOT NULL,
   Contact_partenaire VARCHAR(50) NOT NULL,
   PRIMARY KEY(id_partenaire)
);

CREATE TABLE Epreuve(
   id_epreuve SERIAL,
   Nom_epreuve VARCHAR(50) NOT NULL,
   Nbr_max_equipe INT NOT NULL,
   id_recompense INT NOT NULL,
   PRIMARY KEY(id_epreuve),
   FOREIGN KEY(id_recompense) REFERENCES Recompense(id_recompense)
);

CREATE TABLE equipe(
   id_equipe SERIAL,
   nom_equipe VARCHAR(50) NOT NULL,
   Nom_chef_equipe VARCHAR(50),
   id_epreuve INT NOT NULL,
   id_hack INT,
   PRIMARY KEY(id_equipe),
   FOREIGN KEY(id_epreuve) REFERENCES Epreuve(id_epreuve),
   FOREIGN KEY(id_hack) REFERENCES Hachaton(id_hack)
);

CREATE TABLE Possede(
   id_hack INT,
   id_menstaf INT,
   PRIMARY KEY(id_hack, id_menstaf),
   FOREIGN KEY(id_hack) REFERENCES Hachaton(id_hack),
   FOREIGN KEY(id_menstaf) REFERENCES Menbre_staff(id_menstaf)
);

CREATE TABLE Contenir(
   id_hack INT,
   id_epreuve INT,
   PRIMARY KEY(id_hack, id_epreuve),
   FOREIGN KEY(id_hack) REFERENCES Hachaton(id_hack),
   FOREIGN KEY(id_epreuve) REFERENCES Epreuve(id_epreuve)
);

CREATE TABLE posseder(
   id_equipe INT,
   id_etudiant INT,
   PRIMARY KEY(id_equipe, id_etudiant),
   FOREIGN KEY(id_equipe) REFERENCES equipe(id_equipe),
   FOREIGN KEY(id_etudiant) REFERENCES Etudiant(id_etudiant)
);

CREATE TABLE Noter(
   id_equipe INT,
   id_juge INT,
   PRIMARY KEY(id_equipe, id_juge),
   FOREIGN KEY(id_equipe) REFERENCES equipe(id_equipe),
   FOREIGN KEY(id_juge) REFERENCES Juge(id_juge)
);

CREATE TABLE Sponsoriser(
   id_hack INT,
   id_partenaire INT,
   PRIMARY KEY(id_hack, id_partenaire),
   FOREIGN KEY(id_hack) REFERENCES Hachaton(id_hack),
   FOREIGN KEY(id_partenaire) REFERENCES Partenaire(id_partenaire)
);