DROP SCHEMA IF EXITS public CASCADE;
CREATE SCHEMA public;
CREATE TABLE MembreStaff(
   id_memstaf BIGINT GENERATED BY DEFAULT AS IDENTIY,
   nom_menstaf VARCHAR(50)  NOT NULL,
   adres_mail VARCHAR(50)  NOT NULL,
   Age INTEGER,
   PRIMARY KEY(id_memstaf)
);

CREATE TABLE Recompense(
   id_recompense BIGINT GENERATED BY DEFAULT AS IDENTIY,
   nom_recompense VARCHAR(50)  NOT NULL,
   type_recompense VARCHAR(50)  NOT NULL,
   PRIMARY KEY(id_recompense)
);

CREATE TABLE Epreuve(
   id_Epreuve BIGINT GENERATED BY DEFAULT AS IDENTIY,
   nom_epreuve VARCHAR(50)  NOT NULL,
   nbr_max_Equipe INTEGER NOT NULL,
   id_recompense BIGINT,
   PRIMARY KEY(id_Epreuve),
   FOREIGN KEY(id_recompense) REFERENCES Recompense(id_recompense)
);

CREATE TABLE Mentor(
   id_mentor INTEGER,
   Nom_mentor VARCHAR(50)  NOT NULL,
   Adresse_mail_mentor VARCHAR(50)  NOT NULL,
   Specialite VARCHAR(50)  NOT NULL,
   PRIMARY KEY(id_mentor)
);

CREATE TABLE Compte(
   id_compte INTEGER,
   pseudo VARCHAR(50)  NOT NULL,
   email VARCHAR(50)  NOT NULL,
   role_admin BOOLEAN NOT NULL,
   empreinte_mdp VARCHAR(100)  NOT NULL,
   id_mentor INTEGER,
   PRIMARY KEY(id_compte),
   UNIQUE(id_mentor),
   UNIQUE(pseudo),
   UNIQUE(email),
   UNIQUE(empreinte_mdp),
   FOREIGN KEY(id_mentor) REFERENCES Mentor(id_mentor)
);

CREATE TABLE OrganisateurHackathon(
   id_organisateur BIGINT GENERATED BY DEFAULT AS IDENTIY,
   nom_org VARCHAR(50)  NOT NULL,
   Ad_mail_org VARCHAR(50)  NOT NULL,
   id_compte INTEGER NOT NULL,
   PRIMARY KEY(id_organisateur),
   UNIQUE(id_compte),
   FOREIGN KEY(id_compte) REFERENCES Compte(id_compte)
);

CREATE TABLE Juge(
   id_Juge BIGINT GENERATED BY DEFAULT AS IDENTIY,
   nom_juge VARCHAR(50)  NOT NULL,
   Adresse_mail_juge VARCHAR(50)  NOT NULL,
   Specialite VARCHAR(50)  NOT NULL,
   id_compte INTEGER NOT NULL,
   PRIMARY KEY(id_Juge),
   UNIQUE(id_compte),
   FOREIGN KEY(id_compte) REFERENCES Compte(id_compte)
);

CREATE TABLE Partenaire(
   id_Partenaire BIGINT GENERATED BY DEFAULT AS IDENTIY,
   nom_partenaire VARCHAR(50)  NOT NULL,
   Contact_partenaire VARCHAR(50)  NOT NULL,
   id_compte INTEGER NOT NULL,
   PRIMARY KEY(id_Partenaire),
   UNIQUE(id_compte),
   FOREIGN KEY(id_compte) REFERENCES Compte(id_compte)
);

CREATE TABLE Hackathon(
   id_hack BIGINT GENERATED BY DEFAULT AS IDENTIY,
   nom_Hack VARCHAR(50)  NOT NULL,
   theme_Hach VARCHAR(50)  NOT NULL,
   heure_Deb TIMESTAMP NOT NULL,
   date_Deb DATE,
   date_fin DATE,
   lieu_hack VARCHAR(50)  NOT NULL,
   contact VARCHAR(50) ,
   id_organisateur BIGINT NOT NULL,
   PRIMARY KEY(id_hack),
   FOREIGN KEY(id_organisateur) REFERENCES OrganisateurHackathon(id_organisateur)
);

CREATE TABLE Equipe(
   id_Equipe BIGINT GENERATED BY DEFAULT AS IDENTIY,
   nom_Equipe VARCHAR(50)  NOT NULL,
   nom_chef VARCHAR(50)  NOT NULL,
   code_Equipe VARCHAR(50) ,
   id_hack BIGINT NOT NULL,
   id_Epreuve BIGINT NOT NULL,
   PRIMARY KEY(id_Equipe),
   FOREIGN KEY(id_hack) REFERENCES Hackathon(id_hack),
   FOREIGN KEY(id_Epreuve) REFERENCES Epreuve(id_Epreuve)
);

CREATE TABLE Participant(
   id_Participant BIGINT GENERATED BY DEFAULT AS IDENTIY,
   nom_participant VARCHAR(50) ,
   etablissement_Participant VARCHAR(50) ,
   mail_Participant VARCHAR(50)  NOT NULL,
   id_Equipe BIGINT NOT NULL,
   PRIMARY KEY(id_Participant),
   FOREIGN KEY(id_Equipe) REFERENCES Equipe(id_Equipe)
);

CREATE TABLE Avoir(
   id_hack BIGINT,
   id_memstaf BIGINT,
   PRIMARY KEY(id_hack, id_memstaf),
   FOREIGN KEY(id_hack) REFERENCES Hackathon(id_hack),
   FOREIGN KEY(id_memstaf) REFERENCES MembreStaff(id_memstaf)
);

CREATE TABLE Contenir(
   id_hack BIGINT,
   id_Epreuve BIGINT,
   PRIMARY KEY(id_hack, id_Epreuve),
   FOREIGN KEY(id_hack) REFERENCES Hackathon(id_hack),
   FOREIGN KEY(id_Epreuve) REFERENCES Epreuve(id_Epreuve)
);

CREATE TABLE Noter(
   id_Equipe BIGINT,
   id_Juge BIGINT,
   note NUMERIC(5,2)   NOT NULL,
   PRIMARY KEY(id_Equipe, id_Juge),
   FOREIGN KEY(id_Equipe) REFERENCES Equipe(id_Equipe),
   FOREIGN KEY(id_Juge) REFERENCES Juge(id_Juge)
);

CREATE TABLE Sponsoriser(
   id_hack BIGINT,
   id_Partenaire BIGINT,
   PRIMARY KEY(id_hack, id_Partenaire),
   FOREIGN KEY(id_hack) REFERENCES Hackathon(id_hack),
   FOREIGN KEY(id_Partenaire) REFERENCES Partenaire(id_Partenaire)
);
